spring.application.name=notificationService
server.port=8081

# Kafka bootstrap (внутри Docker Compose сервис называется kafka)
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Consumer group – идентификатор группы, важна для балансировки
spring.kafka.consumer.group-id=notification-group

# Десериализаторы (преобразование байтов в объекты)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Разрешаем десериализацию из любых пакетов (или укажите свои)
spring.kafka.consumer.properties.spring.json.trusted.packages=*



# Красивые цвета
spring.output.ansi.enabled=ALWAYS

# Человеческий формат
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){cyan} %clr(%-5level){} %clr([%thread]){magenta} %clr(%logger{36}){yellow} - %msg%n
logging.pattern.dateformat=HH:mm:ss.SSS


# Для ваших пакетов можно поставить DEBUG во время разработки
logging.level.notificationService=INFO

# Для Spring – можно уменьшить детализацию
logging.level.org.springframework.web=WARN

spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS:false}



spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}